#!/bin/bash
# This script is used for running the tests with proper arguments
# from within Jenkins

set -e
set -u
set -x

if [ -d /results ] ; then
  # Running from Jenkins (RW)
  RESULTS="/results"

  cd "/code"
else
  # Running locally in Docker
  RESULTS="./results"
  mkdir -p "${RESULTS}"
fi
REPORTS=${RESULTS}/reports
if [ -d ${REPORTS} ] ; then
	rm -rf "${REPORTS:?}"/*
else
	mkdir -p ${REPORTS}
fi
busted -o junit > ${REPORTS}/test_busted.xml
WORKSPACE=${RESULTS}/tmp py.test-3 --junit-xml=${REPORTS}/test_dlgcnt.xml ./tests/test_dlgcnt.py
