#!/bin/bash
# This script is used for running the tests with proper arguments
# from within Jenkins

set -e
set -u
set -x

if [ -d /results ] ; then
  # Running from Jenkins (RW)
  RESULTS="/results"

  cd "/code"
else
  # Running locally in Docker
  RESULTS="./results"
  mkdir -p "${RESULTS}"
fi
mkdir -p ${RESULTS}/reports
busted -o junit > ${RESULTS}/test_busted.xml
WORKSPACE=${RESULTS}/tmp py.test-3 --junit-xml=${RESULTS}/test_dlgcnt.xml ./tests/test_dlgcnt.py
